# Numpy Crash Course

NumPy is a python library used for working with arrays.

In this tutorial, we are going to see how to create a numpy object, how to inspect size and shape of a numpy array, how to extract specific set of items from array, how to reverse rows or columns or whole array, how to represent missing values and infinite, how to find min & max and other statistical parameters, how to create a new array from existing array from an array and how to reshape, flatten, rival, etc

In [137]:
import numpy as np

In [138]:
list1 = [0,1,2,3,4]

In [139]:
list1

[0, 1, 2, 3, 4]

#### The above one is list not a numpy array 

In [140]:
arr1d = np.array(list1)

In [141]:
arr1d


array([0, 1, 2, 3, 4])

In [142]:
type(arr1d)

numpy.ndarray

In [143]:
type(list1)

list

#### Main Difference between list and array is that arrays are designed to carry out vectorized operations while list cant be vectorized.

When an array is defined with a size, it cant be increased whereas a list size can be changed

In [144]:
list1.append(5)

In [145]:
list1

[0, 1, 2, 3, 4, 5]

#### If we want to add a number throughout the set of numbers its easy in arrays than in lists

In [146]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [147]:
arr1d + 2

array([2, 3, 4, 5, 6])

#### We cant do elementwise operation in lists

#### If we want to create a 2D array, do the following

In [148]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]

In [149]:
arr2d = np.array(list2)

In [150]:
type(arr2d)      #to find out type of arr2d

numpy.ndarray

In [151]:
arr2d.dtype      #to find out the data type of elements in an array

dtype('int64')

#### If we want to change the datatype of the array elements at the loading tym we can do the following

In [152]:
arr2d = np.array(list2 ,dtype = 'float')

In [153]:
arr2d.dtype

dtype('float64')

In [154]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

#### If we want to change datatype of an already created numpy array, then do the following

In [155]:
arr2d.astype('int')

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [156]:
arr2d.dtype

dtype('float64')

#### Here since we have not taken the result into arr2d it has just shown the output but didnt make changes to original array. To do that,

In [157]:
arr2d = arr2d.astype('int')

In [158]:
arr2d.dtype

dtype('int64')

#### We can also change it to a string datatype

In [159]:
str_arr2d = arr2d.astype('str')
str_arr2d

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U21')

In [160]:
str_arr2d.dtype

dtype('<U21')

#### One more difference between array and list is that array contains only objects of same kind whereas objects of different datatype can be present in a list

In [161]:
list1

[0, 1, 2, 3, 4, 5]

In [162]:
list1.append('6')      #appending a string into a list that contains all integers which is not possible in arrays

In [163]:
list1

[0, 1, 2, 3, 4, 5, '6']

#### To convert a numpy array into a list

In [164]:
np2list = arr2d.tolist()

In [165]:
np2list

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [166]:
type(np2list)

list

#### Inspecting shape and size

In [167]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [168]:
arr2d = arr2d.astype('float')

In [169]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [170]:
print('Shape:',arr2d.shape)

Shape: (3, 3)


In [171]:
arr2d.dtype

dtype('float64')

In [172]:
arr2d.size      #total 9 elements are present in the arr2d

9

In [173]:
arr2d.ndim      #to get the dimension of an array

2

In [174]:
arr1d.ndim

1

#### Extracting specific items from the array

In [175]:
arr1d

array([0, 1, 2, 3, 4])

In [176]:
arr1d = arr1d**2

In [177]:
arr1d

array([ 0,  1,  4,  9, 16])

In [178]:
b = arr1d[0]     # get the element at 0th index
b

0

In [179]:
b = arr1d[2]     # get the element at 2nd index
b

4

In [180]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [181]:
arr2d[0]        # get the 0th row

array([1., 1., 1.])

In [182]:
arr2d[0][0]     # get the element at 0th row and 0th column      #[R][C]

1.0

In [183]:
arr2d[1][2]

2.0

#### If we want to select some numbers with conditions

In [184]:
boolarr = arr2d<3

In [185]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [186]:
arr2d[boolarr]

array([1., 1., 1., 2., 2., 2.])

#### Reverse the rows/columns or the whole array

In [187]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
arr2d[::-1,]          #reverse the rows

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [189]:
arr2d[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### Representing null and infinite values in numpy array

In [190]:
np.nan

nan

In [191]:
np.inf

inf

In [192]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
arr2d[0][0] = np.nan     #this means NaN and inf are floating values

ValueError: cannot convert float NaN to integer

In [194]:
arr2d = arr2d.astype('float')

In [195]:
arr2d[0][0] = np.nan
arr2d[0][1] = np.inf
arr2d

array([[nan, inf,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

#### Inorder to check whether an array contains any null or inf value

In [199]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [200]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [202]:
np.isnan(arr2d).sum()

1

In [203]:
np.isinf(arr2d).sum()

1

#### If we want to replace any infinite value or get the position

In [205]:
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [207]:
arr2d[missing_flag]

array([nan, inf])

In [209]:
arr2d[missing_flag] = 0
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Statistical Operations on arrays

In [219]:
arr2d.mean()       #find mean

4.666666666666667

In [220]:
arr2d.max()        #find mac

9.0

In [221]:
arr2d.min()        #find min

0.0

In [222]:
arr2d.std()         #find standard deviation

3.0550504633038935

In [223]:
arr2d.var()        #find variance

9.333333333333334

In [224]:
arr2d.cumsum()      #find cummulative sum

array([ 0.,  0.,  3.,  7., 12., 18., 25., 33., 42.])

#### Create an array from existing array

In [228]:
arr = arr2d[:2,:2]


In [229]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [230]:
arr

array([[0., 0.],
       [4., 5.]])

In [231]:
arr2d[1:3,1:3]

array([[5., 6.],
       [8., 9.]])

#### Reshaping

In [232]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [233]:
arr2d.shape

(3, 3)

In [238]:
arr2d.reshape(9,1)     #doesnt change the shape of original array..returns array with the shape givem

array([[0.],
       [0.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [242]:
arr2d.ndim

2

In [243]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [244]:
arr2d.flatten()

array([0., 0., 3., 4., 5., 6., 7., 8., 9.])

In [245]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [247]:
arr2d.ravel()

array([0., 0., 3., 4., 5., 6., 7., 8., 9.])

In [248]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Both the above methods look same,but the difference lies here

In [250]:
a = arr2d.flatten()
a

array([0., 0., 3., 4., 5., 6., 7., 8., 9.])

In [251]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [252]:
b = arr2d.ravel()
b

array([0., 0., 3., 4., 5., 6., 7., 8., 9.])

In [253]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [254]:
a[0] = -1
a  #copy

array([-1.,  0.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [255]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [258]:
b[0] = -1
b  #reference

array([-1.,  0.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [259]:
arr2d

array([[-1.,  0.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

ravel() doesn't allocate new memory and hence the changes are reflected back whereas flatten() allocates new memory and creates a copy of the original object. Therefore ravel() is memory efficient when using large datasets

#### Creating Sequence, Repetitions and random numbers

In [262]:
np.arange(1,10, dtype = 'float')     # start value is included whereas stop value is not included

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [266]:
np.arange(2,51,2)   #to generate even numbers bw 1 and 50 including 1 and 50

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

Understanding Linspace and Logspace:

In np.linspace() there is an option which asks us how many numbers we want between start and stop, whether we want to include the last number or not(by default it is True, if we dont want make it False).
linspace() return evenly spaced numbers over a specified interval linearly.
logspace() return numbers spaced evenly on a log scale.

In [281]:
np.linspace(1,25,50)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [282]:
np.logspace(1,25,50)

array([1.00000000e+01, 3.08884360e+01, 9.54095476e+01, 2.94705170e+02,
       9.10298178e+02, 2.81176870e+03, 8.68511374e+03, 2.68269580e+04,
       8.28642773e+04, 2.55954792e+05, 7.90604321e+05, 2.44205309e+06,
       7.54312006e+06, 2.32995181e+07, 7.19685673e+07, 2.22299648e+08,
       6.86648845e+08, 2.12095089e+09, 6.55128557e+09, 2.02358965e+10,
       6.25055193e+10, 1.93069773e+11, 5.96362332e+11, 1.84206997e+12,
       5.68986603e+12, 1.75751062e+13, 5.42867544e+13, 1.67683294e+14,
       5.17947468e+14, 1.59985872e+15, 4.94171336e+15, 1.52641797e+16,
       4.71486636e+16, 1.45634848e+17, 4.49843267e+17, 1.38949549e+18,
       4.29193426e+18, 1.32571137e+19, 4.09491506e+19, 1.26485522e+20,
       3.90693994e+20, 1.20679264e+21, 3.72759372e+21, 1.15139540e+22,
       3.55648031e+22, 1.09854114e+23, 3.39322177e+23, 1.04811313e+24,
       3.23745754e+24, 1.00000000e+25])

In [284]:
np.zeros((2,2))    # to generate a 2X2 matrix of zeros

array([[0., 0.],
       [0., 0.]])

In [285]:
np.ones((2,2))    # to generate a 2X2 matrix of ones

array([[1., 1.],
       [1., 1.]])

Given an array if we want it to be repeated n times,

In [286]:
a = [1,2,3]

In [287]:
a

[1, 2, 3]

In [289]:
np.tile(a, reps = 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [295]:
arr2d

array([[-1.,  0.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [305]:
np.tile(arr2d, reps = 3)

array([[-1.,  0.,  3., -1.,  0.,  3., -1.,  0.,  3.],
       [ 4.,  5.,  6.,  4.,  5.,  6.,  4.,  5.,  6.],
       [ 7.,  8.,  9.,  7.,  8.,  9.,  7.,  8.,  9.]])

In [303]:
np.repeat(arr2d, repeats = 3)

array([-1., -1., -1.,  0.,  0.,  0.,  3.,  3.,  3.,  4.,  4.,  4.,  5.,
        5.,  5.,  6.,  6.,  6.,  7.,  7.,  7.,  8.,  8.,  8.,  9.,  9.,
        9.])

In [300]:
np.repeat(arr2d, repeats = 3, axis = 0)

array([[-1.,  0.,  3.],
       [-1.,  0.,  3.],
       [-1.,  0.,  3.],
       [ 4.,  5.,  6.],
       [ 4.,  5.,  6.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 7.,  8.,  9.],
       [ 7.,  8.,  9.]])

In [301]:
np.repeat(arr2d, repeats = 3, axis = 1)

array([[-1., -1., -1.,  0.,  0.,  0.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  8.,  8.,  8.,  9.,  9.,  9.]])

Random Number Generation

In [325]:
np.random.rand(3,3)      #Uniformly distributed random number b/w (0 and 1) by default

array([[0.54726264, 0.21222931, 0.99195815],
       [0.69717856, 0.26665249, 0.17606965],
       [0.66912741, 0.71368727, 0.47422648]])

In [315]:
np.random.randn(3,3)     #Normally distributed

array([[ 0.04960936,  2.67048301, -0.87076863],
       [-1.45752349,  0.3277836 ,  1.29579704],
       [-2.01752445, -1.24146039, -0.49777038]])

In [329]:
np.random.randint(1,10)    #generating random integer b/w given intervals and with the size

2

In [358]:
 np.random.randint(1,10,(3,3))

array([[5, 6, 2],
       [7, 8, 1],
       [8, 3, 2]])

In [370]:
np.random.seed(0)       #If we want same random number everytime we need to set the seed
np.random.randint(1,10,(3,3))

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

#### Get Unique items and the counts from an array

In [373]:
arr2d = np.array([[-1,1,0],[2,2,2],[3,3,3]])
arr2d

array([[-1,  1,  0],
       [ 2,  2,  2],
       [ 3,  3,  3]])

In [374]:
np.unique(arr2d)

array([-1,  0,  1,  2,  3])

In [376]:
uniques, counts = np.unique(arr2d,return_counts = True)

In [377]:
uniques

array([-1,  0,  1,  2,  3])

In [378]:
counts

array([1, 1, 1, 3, 3])

## Numpy Crash Course Part 2

In this tutorial, we are going to see some advanced data processing in numpy.

We are goint to see how to get index location that satifies certain condition, how to import and export csv data, how to handle datasets that have both number and text.(Before we know array can only handle same data type, now we will see how it can handle more than one type)

#### Get index loc that satisfies given condition

In [383]:
arr = np.array([8,94,8,56,1,3,14,7])

In [384]:
arr

array([ 8, 94,  8, 56,  1,  3, 14,  7])

In [385]:
index_gt10 = np.where(arr>10)            #Get all the indexes that are >10

In [386]:
index_gt10

(array([1, 3, 6]),)

In [390]:
arr[index_gt10]                         #to print those values

array([94, 56, 14])

In [391]:
arr[arr>10]                             #here we wont get index, we only get values

array([94, 56, 14])

In [393]:
arr>10                                  #creates a boolean array

array([False,  True, False,  True, False, False,  True, False])

In [396]:
np.where(arr>10, 'gt10', 'lt10')       #prints 'gt10' where values are >10 and lt10 where <10

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'gt10', 'lt10'],
      dtype='<U4')

In [398]:
arr.max()                               #get max value

94

In [399]:
arr.argmax()                            #get index of maximum value

1

Similarly we have min() and argmin()

#### Read and Write .csv files

For doing this we have two formats,

1. np.genfromtxt(),

2. np.loadtxt()

In [419]:
dat = np.genfromtxt('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv',delimiter = ',', skip_header = 1,filling_values = -1000, dtype = 'float')

In [422]:
np.set_printoptions(suppress = True)
dat

array([[    5.1,     3.5,     1.4,     0.2, -1000. ],
       [    4.9,     3. ,     1.4,     0.2, -1000. ],
       [    4.7,     3.2,     1.3,     0.2, -1000. ],
       [    4.6,     3.1,     1.5,     0.2, -1000. ],
       [    5. ,     3.6,     1.4,     0.2, -1000. ],
       [    5.4,     3.9,     1.7,     0.4, -1000. ],
       [    4.6,     3.4,     1.4,     0.3, -1000. ],
       [    5. ,     3.4,     1.5,     0.2, -1000. ],
       [    4.4,     2.9,     1.4,     0.2, -1000. ],
       [    4.9,     3.1,     1.5,     0.1, -1000. ],
       [    5.4,     3.7,     1.5,     0.2, -1000. ],
       [    4.8,     3.4,     1.6,     0.2, -1000. ],
       [    4.8,     3. ,     1.4,     0.1, -1000. ],
       [    4.3,     3. ,     1.1,     0.1, -1000. ],
       [    5.8,     4. ,     1.2,     0.2, -1000. ],
       [    5.7,     4.4,     1.5,     0.4, -1000. ],
       [    5.4,     3.9,     1.3,     0.4, -1000. ],
       [    5.1,     3.5,     1.4,     0.3, -1000. ],
       [    5.7,     3.8,   

In [423]:
dat.shape

(150, 5)

In [424]:
dat[:3]

array([[    5.1,     3.5,     1.4,     0.2, -1000. ],
       [    4.9,     3. ,     1.4,     0.2, -1000. ],
       [    4.7,     3.2,     1.3,     0.2, -1000. ]])

In [430]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv',delimiter = ',', skip_header = 1, dtype = None)

/home/vishwa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [431]:
data2[:3]

array([(5.1, 3.5, 1.4, 0.2, b'setosa'), (4.9, 3. , 1.4, 0.2, b'setosa'),
       (4.7, 3.2, 1.3, 0.2, b'setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S10')])

In [433]:
np.savetxt('data.csv',dat, delimiter = ',')

#### Concatenation row wise and column wise

In [476]:
np.random.seed(0)
arr1 = np.random.randint(1,10,size = (4,4))
arr1

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8]])

In [449]:
np.random.seed(1)
arr2 = np.random.randint(1,10,size = (4,4))
arr2

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3],
       [5, 3, 5, 8]])

There are three ways of doing this

1. np.concatenate()

2. np.vstack()

3. np.r_()

In [450]:
np.concatenate([arr1,arr2], axis = 0)

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8],
       [6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3],
       [5, 3, 5, 8]])

In [451]:
np.vstack([arr1,arr2])

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8],
       [6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3],
       [5, 3, 5, 8]])

In [453]:
np.r_[arr1,arr2]

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8],
       [6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3],
       [5, 3, 5, 8]])

In [454]:
np.concatenate([arr1,arr2],axis = 1)

array([[6, 1, 4, 4, 6, 9, 6, 1],
       [8, 4, 6, 3, 1, 2, 8, 7],
       [5, 8, 7, 9, 3, 5, 6, 3],
       [9, 2, 7, 8, 5, 3, 5, 8]])

In [455]:
np.hstack([arr1,arr2])

array([[6, 1, 4, 4, 6, 9, 6, 1],
       [8, 4, 6, 3, 1, 2, 8, 7],
       [5, 8, 7, 9, 3, 5, 6, 3],
       [9, 2, 7, 8, 5, 3, 5, 8]])

In [456]:
np.c_[arr1,arr2]

array([[6, 1, 4, 4, 6, 9, 6, 1],
       [8, 4, 6, 3, 1, 2, 8, 7],
       [5, 8, 7, 9, 3, 5, 6, 3],
       [9, 2, 7, 8, 5, 3, 5, 8]])

#### Sort an array

In [478]:
arr1

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8]])

In [479]:
np.sort(arr1)             #by default it sorts row-wise

array([[1, 4, 4, 6],
       [3, 4, 6, 8],
       [5, 7, 8, 9],
       [2, 7, 8, 9]])

In [480]:
arr1

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8]])

In [481]:
np.sort(arr1,axis = 0)

array([[5, 1, 4, 3],
       [6, 2, 6, 4],
       [8, 4, 7, 8],
       [9, 8, 7, 9]])

The problem of this way of sorting is that the array is being sorted by rows/columns independently.
Suppose if there are any relationship among columns, like if a row belongs a person then the data is lost. So to solve this, we go for Argumentsort

In [487]:
arr1[:,0]

array([6, 8, 5, 9])

In [491]:
sorted_index = arr1[:,0].argsort()         # returns the index of sorted values,i.e. 1st element of the sorted array is in 2nd index and 2nd element is on 0th index

In [493]:
arr1

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8]])

In [494]:
arr1[sorted_index]

array([[5, 8, 7, 9],
       [6, 1, 4, 4],
       [8, 4, 6, 3],
       [9, 2, 7, 8]])

#### Working with dates

In [497]:
d = np.datetime64('2020-07-23 16:45:00')
d

numpy.datetime64('2020-07-23T16:45:00')

In [499]:
d + 1          #added 1 second to the date

numpy.datetime64('2020-07-23T16:45:01')

In [501]:
d + 10         #added 1 second to the date

numpy.datetime64('2020-07-23T16:45:10')

If we want to add days,we can use 

In [503]:
oneday = np.timedelta64(1,'D')
oneday

numpy.timedelta64(1,'D')

In [504]:
d + oneday

numpy.datetime64('2020-07-24T16:45:00')

In [505]:
onemin = np.timedelta64(1,'m')
onemin

numpy.timedelta64(1,'m')

In [506]:
d + onemin

numpy.datetime64('2020-07-23T16:46:00')

To create a sequence of dates,

In [510]:
dates = np.arange(np.datetime64('2020-07-23'),np.datetime64('2020-08-23'))      #by defaults increments one day
dates

array(['2020-07-23', '2020-07-25', '2020-07-27', '2020-07-29',
       '2020-07-31', '2020-08-02', '2020-08-04', '2020-08-06',
       '2020-08-08', '2020-08-10', '2020-08-12', '2020-08-14',
       '2020-08-16', '2020-08-18', '2020-08-20', '2020-08-22'],
      dtype='datetime64[D]')

In [511]:
dates = np.arange(np.datetime64('2020-07-23'),np.datetime64('2020-08-23'),3)      #by defaults increments one day
dates

array(['2020-07-23', '2020-07-26', '2020-07-29', '2020-08-01',
       '2020-08-04', '2020-08-07', '2020-08-10', '2020-08-13',
       '2020-08-16', '2020-08-19', '2020-08-22'], dtype='datetime64[D]')

#### Vectorize

In [512]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2
    
foo(10)

5.0

In [513]:
foo(11)

121

If we have a large numpy array and want to perform this operation, we need to vectorize this

In [514]:
foo_v = np.vectorize(foo, otypes = [float])

In [516]:
arr1

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9],
       [9, 2, 7, 8]])

In [517]:
foo_v(arr1)

array([[ 3.,  1.,  2.,  2.],
       [ 4.,  2.,  3.,  9.],
       [25.,  4., 49., 81.],
       [81.,  1., 49.,  4.]])